#!/usr/bin/env bash

# check for X server if running on WSL
if test -f /proc/version && grep -qi microsoft /proc/version; then
  if ! command -v xset &>/dev/null; then
    echo "A required dependency is missing from your system!"
    echo "Run this command to install it:"
    echo "    sudo apt-get install x11-xserver-utils"
    exit 1
  fi
  # use xset to check if X server is running
  if ! timeout 1s xset q &>/dev/null; then
    echo "X server is not running! Run XLaunch from Windows and try again."
    exit 1
  fi
fi

# install cypress globally if not installed
if ! command -v cypress &>/dev/null; then
  npm install cypress@8.4.0 --global
fi

cypress open --project . --config-file "spec/config.json"
